version: '3'
services:
    drupal:
      build:
        dockerfile: docker/drupal/Dockerfile-16
        context: .
        args:
          PHP_VERSION: 7.3
          DRUPAL_VERSION: 7.66
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./app/drupal/sites/default/settings.php:/var/www/html/sites/default/settings.php
        - ./app/drupal/sites/all/libraries:/var/www/html/sites/all/libraries
        - ./app/drupal/sites/all/modules:/var/www/html/sites/all/modules
        - ./app/drupal/sites/all/themes:/var/www/html/sites/all/themes
        # - ./app/drupal/misc:/var/www/html/misc
        - ./app/drupal/status.php:/var/www/html/status.php
      env_file:
        - dev.env
        #- prod.env

    # aws s3 ls --profile cmp-developer s3://app_go_iemyxvinzbc/backup/database/prod/
    mysql:
      image: mysql:5.7
      user: root
      #command: mysqld --skip-grant-tables
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=go
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
      volumes:
        - ./data/mysql:/var/lib/mysql:rw
        - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./docker/mysql/rootfs/etc/mysql/conf.d/my-extras.cnf:/etc/mysql/conf.d/my-extras.cnf:rw
