<?php
/**
 * @file
 * Openid_connect related hook implemenations for the Audit log module.
 */

/**
 * Implements hook_openid_connect_post_authorize().
 */
function audit_log_openid_connect_openid_connect_post_authorize($tokens, $account, $userinfo, $client_name) {
  audit_log($account, 'user', 'openid-connect-post-authorize', $account, NULL, REQUEST_TIME, array(
    'message' => format_string('Authorized @name.', array('@name' => $account->name)),
  ));
}
/**
 * Implements hook_audit_log_action_options().
 *
 * Provide actions related to user actions
 */
function audit_log_openid_connect_audit_log_action_options() {
  return drupal_map_assoc(array(
    'hybridauth-user-created',
    'hybridauth-user-identity-added',
    'hybridauth-user-identity-deleted',
    'hybridauth-user-login',
    'hybridauth-user-blocked',
  ));
}
