FROM ubuntu:xenial
MAINTAINER DAN

ARG PHP_VERSION
ENV PHP_VERSION ${PHP_VERSION:-7.3}

ARG DRUPAL_VERSION
ENV DRUPAL_VERSION ${DRUPAL_VERSION:-7.67}

ARG S6_VERSION
ENV S6_VERSION ${S6_VERSION:-1.22.1.0}

############ UBUNTU #############################################################

#ENV LANGUAGE    en_US.UTF-8
#ENV LANG        en_US.UTF-8
#ENV LC_ALL      en_US.UTF-8
#ENV LC_MESSAGES en_US.UTF-8

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common unattended-upgrades curl git vim \
    #locales \
    #&& locale-gen en_US.UTF-8 \
    #&& localedef -i en_US -f UTF-8 en_US.UTF-8 \
    && unattended-upgrade -d \
    ############ PHP / NGINX #############################################################
    && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php \
    && curl http://nginx.org/keys/nginx_signing.key -o /tmp/nginx_signing.key \
    && apt-key add /tmp/nginx_signing.key \
    && echo "deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx" >> /etc/apt/sources.list \
    && echo "deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx" >> /etc/apt/sources.list \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        make gettext-base unzip vim \
        mysql-client \
        nginx \
        php${PHP_VERSION}-dev \
        php${PHP_VERSION}-cli \
        php${PHP_VERSION}-fpm \
        php${PHP_VERSION}-bcmath \
        php${PHP_VERSION}-bz2 \
        php${PHP_VERSION}-curl \
        php${PHP_VERSION}-gd \
        php${PHP_VERSION}-intl \
        php${PHP_VERSION}-json \
        php${PHP_VERSION}-ldap \
        php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-mysql \
        php${PHP_VERSION}-opcache \
        php${PHP_VERSION}-readline \
        php${PHP_VERSION}-recode \
        php${PHP_VERSION}-xml \
        php${PHP_VERSION}-xsl \
        php${PHP_VERSION}-zip \
        php-igbinary \
        php-redis \
        python3 \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && cd /tmp \
        && curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" \
        && unzip awscli-bundle.zip \
        && ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws \
        && rm -rf /tmp/awscli-bundle* \
    && ln -s /etc/php/${PHP_VERSION} /etc/php/$(echo $PHP_VERSION | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//') \
    && ln -s /etc/php/${PHP_VERSION} /etc/php/curr \
    && ln -s /usr/sbin/php-fpm${PHP_VERSION} /usr/sbin/php-fpm \
    && ln -s /etc/init.d/php${PHP_VERSION}-fpm /etc/init.d/php-fpm \
    && apt-get -y autoclean \
        && apt-get -y clean \
        && apt-get -y autoremove \
        && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && cd /usr/src \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod a+x /usr/local/bin/composer \
    && mkdir -p -m 664 \
        /var/log/nginx \
        /var/log/php \
        /var/lib/php/sessions \
        /var/www/ \
        /var/www/html \
    && chown -R www-data:www-data \
        /var/log/nginx \
        /var/log/php \
        /var/lib/php/sessions \
        /var/www \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stdout /var/log/nginx/error.log \
    && ln -sf /dev/stdout /var/log/php/cli_error.log \
    && ln -sf /dev/stdout /var/log/php/fpm_error.log \
    && ln -sf /dev/stdout /var/log/php/fpm_slow.log \
    && ln -sf /dev/stdout /var/log/php-fpm.log \
    && cd /tmp \
    && curl -L -s https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-amd64.tar.gz | tar xvzf - -C / \
    ############ DRUPAL #############################################################
    && composer global require drush/drush:~8.1 \
    && composer global update --no-plugins --no-scripts \
    && ln -s /root/.composer/vendor/bin/drush /usr/local/bin/drush \
    && chmod a+x /usr/local/bin/drush /root/.composer/vendor/bin/drush \
    && drush dl -y drupal-${DRUPAL_VERSION} \
        --destination=/var/www --drupal-project-rename=html \
    && chown -R www-data:www-data \
        /var/www \
    && chmod g+x \
       /var/www \
       /var/www/html

COPY docker/drupal/rootfs/ /
RUN cp -R /etc/php/all/* /etc/php/${PHP_VERSION}/

############ APPLICATION #############################################################

COPY app/drupal/sites /var/www/html/sites
COPY app/drupal/misc  /var/www/html/misc
COPY app/drupal/status.php  /var/www/html/status.php

WORKDIR /var/www/html
EXPOSE 80 443

ENTRYPOINT [ "/init" ]
